---
-   name: Install pip3
    apt:
      name:
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: present
      update_cache: yes
      cache_valid_time: 86400 #One day

-   name: Install DNSeval
    pip:
      name:
        - dnsdiag

-   name: Install Passlib
    pip:
      name:
        - passlib

-   name: Install MC
    apt:
      name:
        - mc

-   name: Install vnstat
    apt:
      name:
        - vnstat

-   name: Install htop
    apt:
      name:
        - htop