version: '3.7'
services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8085:80'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - ./storage/logs:/var/log/icl
            - .:/app
        networks:
            - icl
        depends_on:
            - services-mysql

    services-mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "33069:3306"
        environment:
            MYSQL_DATABASE: icl
            MYSQL_USER: icl
            MYSQL_PASSWORD: icl
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: icl
        volumes:
            - ./storage/app/docker/db/mysql:/var/lib/mysql
            - ./storage/app/docker/logs:/var/log/icl
        networks:
            - icl

networks:
    icl:
        driver: bridge
volumes:
    sailmysql:
        driver: local
