#!/usr/bin/env bash

zerobot renew 1>>/var/log/icl/zerobot_pipe_output.log 2> >(tee /var/log/icl/zerobot_pipe_error.log >&2) && (docker ps | grep 'icl-app' | awk '{print $1}' | xargs --no-run-if-empty docker restart >>/var/log/icl/zerobot_pipe_output.log)
